name: Streamlit Deployment

on:
  push:
    branches:
      - main  # Adjust this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Adjust this to your Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Streamlit app
      run: streamlit run your_app.py  # Replace with the name of your Streamlit app file
